import { useEffect, useState } from 'react';import GraphView from '../components/GraphView';import ChatStream from '../components/ChatStream';import { api } from '../api/client';
export default function RunStudio(){
const [messages,setMessages]=useState<any[]>([]);const [talk,setTalk]=useState(false);const [consensus,setConsensus]=useState(1);const [tokenBudget,setTokenBudget]=useState(1000);const [file,setFile]=useState<File|null>(null)
const agents=[{name:'A1'},{name:'A2'},{name:'A3'}];
const run=async()=>{const teams=await api('/api/teams');if(!teams.length)return;const out=await api('/api/runs',{method:'POST',body:JSON.stringify({team_id:teams[0].id,prompt:'Hello',max_turns:4,max_seconds:30,token_budget:tokenBudget,consensus_threshold:consensus,reflection:true})});setMessages(out.messages||[])};
const pause=()=>api('/api/runs/1/pause',{method:'POST'});const resume=()=>api('/api/runs/1/resume',{method:'POST'});
const upload=async()=>{if(!file) return;const fd=new FormData();fd.append('file',file);await fetch('http://localhost:8000/api/runs/1/attachments',{method:'POST',body:fd})}
useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')run();if(e.key==='Escape')pause()};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[])
return <div><h2>Run Studio</h2><label><input type='checkbox' checked={talk} onChange={e=>setTalk(e.target.checked)}/>Talk to the Team</label><div><label>Consensus {consensus}</label><input type='range' min='1' max='3' value={consensus} onChange={e=>setConsensus(Number(e.target.value))}/></div><div><label>Token budget</label><input value={tokenBudget} onChange={e=>setTokenBudget(Number(e.target.value))}/></div><input type='file' onChange={e=>setFile(e.target.files?.[0]||null)}/><button onClick={upload}>Upload Attachment</button><button onClick={run}>Start Run</button><button onClick={pause}>Pause</button><button onClick={resume}>Resume</button><a href='http://localhost:8000/api/snapshot.png?run_id=1'>Download Snapshot</a><GraphView agents={agents}/><ChatStream messages={messages}/></div>}
